# This is a basic workflow to help you get started with Actions

name: Docker Image CI

# Controls when the workflow will run
on:
  create:
    tags:
      - v*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          DOCKER_PROJECT: ${{secrets.DOCKER_PROJECT}}
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}

        run: |
          echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USER --password-stdin

      - name: Format repo name
        run: echo 'REPO_NAME=$(echo ${GITHUB_REPOSITORY##*/} | tr "[:upper:]" "[:lower:]")' >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build -t ${{secrets.DOCKER_USER}}/${{ env.REPO_NAME }}:${GITHUB_REF##*/} .

      # Runs a single command using the runners shell
      - name: Docker push
        run: docker push ${{secrets.DOCKER_USER}}/${{ env.DOCKER_PROJECT }}:${{ env.RELEASE_VERSION }}
